package kz.model;
// Generated 04.02.2016 23:24:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Exercises generated by hbm2java
 */
@Entity
@Table(name="exercises"
    ,catalog="diploma_work"
)
public class Exercises  implements java.io.Serializable {


     private int id;
     private int ID_theme;
     private String name;
     private String description;
     
    public Exercises() {
    }

    public Exercises(int id, int ID_theme, String name, String description) {
       this.id = id;
       this.ID_theme = ID_theme;
       this.name = name;
       this.description = description;
    }
   
    @Id     
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="ID_theme", nullable=false)
    public int getID_theme() {
        return this.ID_theme;
    }
    
    public void setID_theme(int ID_theme) {
        this.ID_theme = ID_theme;
    }

    
    @Column(name="description", nullable=false, length=65535)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="theme", nullable=false, length=100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}


