package kz.model;
// Generated 04.02.2016 23:24:16 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.List;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Themes generated by hbm2java
 */
@Entity
@Table(name="themes"
    ,catalog="diploma_work"
)
public class Themes  implements java.io.Serializable {


     private int id;
     private String theme;
     private String themeDoc;
     
     private List<Exercises> themeExercises = new ArrayList<>();
     private Videos video;

    public Themes() {
    }

    public Themes(int id, String theme, String themeDoc) {
       this.id = id;
       this.theme = theme;
       this.themeDoc = themeDoc;
    }
   
    @Id     
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="theme", nullable=false, length=100)
    public String getTheme() {
        return this.theme;
    }
    
    public void setTheme(String theme) {
        this.theme = theme;
    }

    
    @Column(name="theme_doc", nullable=false, length=100)
    public String getThemeDoc() {
        return this.themeDoc;
    }
    
    public void setThemeDoc(String themeDoc) {
        this.themeDoc = themeDoc;
    }    
    
    
    @OneToMany
    @JoinColumn(name = "ID_theme")
    public List<Exercises> getThemeExercises(){
        return this.themeExercises;
    }
    
    public void setThemeExercises(List<Exercises> themeExercises){
        this.themeExercises = themeExercises;
    }
    
    @OneToMany
    @JoinColumn(name = "ID_theme")
    public Videos getThemeVideo(){
        return this.video;
    }
    
    public void setThemeVideo(Videos video){
        this.video = video;
    }
}


