package kz.model;
// Generated 04.02.2016 23:24:16 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name="users"
    ,catalog="diploma_work"
    , uniqueConstraints = @UniqueConstraint(columnNames={"email","password"}) 
)
public class Users  implements java.io.Serializable {


     private int id;
     private String name;
     private String surname;
     private String email;
     private String password;
     
    public Users() {
    }

    public Users(int id, String name, String surname, String email, String password) {
       this.id = id;
       this.name = name;
       this.surname = surname;
       this.email = email;
       this.password = password;
    }
   
     @Id     
    @Column(name="ID", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="surname", nullable=false, length=50)
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="email", unique=true, nullable=false, length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name="password", unique=true, nullable=false, length=50)
    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }




}


